name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  node-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]  # test against multiple Node versions
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test -- --coverage

      - name: Build
        run: npm run build

      - name: Upload build artifact
        if: matrix.node-version == '20.x'
        uses: actions/upload-artifact@v4
        with:
          name: app-dist
          path: dist/
